all:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/bazaar_root_key

  children:
    nodes:
      hosts:
        bazaar-1:
          ansible_host: 192.168.1.195
          node_id: 1
        bazaar-2:
          ansible_host: 192.168.1.11
          node_id: 2
        bazaar-3:
          ansible_host: 192.168.1.151
          node_id: 3
    # vms:
    #   hosts:
    #     vm10:
    #       ansible_host: 192.168.1.10
    #     vm20:
    #       ansible_host: 192.168.1.20
    #     vm21:
    #       ansible_host: 192.168.1.21
    #     vm30:
    #       ansible_host: 192.168.1.30
    #     vm31:
    #       ansible_host: 192.168.1.31 
