all:
  vars:
    ansible_python_interpreter: auto_silent
  hosts:
    bazaar-1:
      ansible_host: 192.168.1.195
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/bazaar_root_key
    bazaar-2:
      ansible_host: 192.168.1.11
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/bazaar_root_key
    bazaar-3:
      ansible_host: 192.168.1.151
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/bazaar_root_key