---
# - name: Download Consul binary
#   get_url:
#     url: "https://releases.hashicorp.com/consul/1.15.4/consul_1.15.4_linux_amd64.zip"
#     dest: "/tmp/consul.zip"

# - name: Unzip Consul binary
#   unarchive:
#     src: "/tmp/consul.zip"
#     dest: "/usr/local/bin"
#     remote_src: true

- name: Create Consul system user
  user:
    name: consul
    create_home: no
    shell: /bin/false

- name: Create Consul directories
  file:
    path: "{{ item }}"
    state: directory
    owner: consul
    group: consul
    mode: 0644
    mode: "0755"
  loop:
    - "{{ consul_data_dir }}"
    - "{{ consul_config_dir }}"

- name: Create Consul configuration file
  ansible.builtin.template:
    src: consul_configuration.hcl.j2
    dest: "{{ consul_config_dir }}/consul.hcl"
    owner: consul
    group: consul
    mode: 0644

- name: Create Consul server configuration file
  ansible.builtin.template:
    src: consul_server.hcl.j2
    dest: "{{ consul_config_dir }}/server.hcl"
    owner: consul
    group: consul
    mode: 0644

- name: Create Consul server configuration file
  ansible.builtin.template:
    src: consul_client.hcl.j2
    dest: "{{ consul_config_dir }}/client.hcl"
    owner: consul
    group: consul
    mode: 0644

- name: Create Consul systemd service
  copy:
    dest: /etc/systemd/system/consul.service
    content: |
      [Unit]
      Description=Consul
      After=network.target

      [Service]
      User=consul
      ExecStart=/usr/local/bin/consul agent -config-dir /etc/consul.d
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target

- name: Enable and start Consul service
  systemd:
    name: consul
    enabled: true
    daemon_reload: true
    state: started
