all:
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: ~/.ssh/vm_key
    ansible_ssh_common_args: -o StrictHostKeyChecking=no

  children:
    pve_nodes:
      hosts:
        bazaar-1:
          ansible_host: 192.168.1.195
          node_id: 1
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/bazaar_root_key          
        bazaar-2:
          ansible_host: 192.168.1.11
          node_id: 2
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/bazaar_root_key 
        bazaar-3:
          ansible_host: 192.168.1.151
          node_id: 3
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/bazaar_root_key 
    nomad_hosts:
      hosts:
        nomad-110:
          ansible_host: 192.168.1.10
        nomad-221:
          ansible_host: 192.168.1.21
        # vm222:
        #   ansible_host: 192.168.1.22
        nomad-331:
          ansible_host: 192.168.1.31
        # vm332:
        #   ansible_host: 192.168.1.32
    # vault_hosts:
    #   hosts:
    #     vm110:
    #       ansible_host: 192.168.1.10
    # consul_hosts:
    #   hosts:
    #     vm110:
    #       ansible_host: 192.168.1.10   