all:
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: ~/.ssh/vm_key
    ansible_ssh_common_args: -o StrictHostKeyChecking=no

  children:
    pve_nodes:
      hosts:
        bazaar-1:
          ansible_host: 192.168.1.195
          node_id: 1
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/bazaar_root_key          
        bazaar-2:
          ansible_host: 192.168.1.11
          node_id: 2
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/bazaar_root_key 
        bazaar-3:
          ansible_host: 192.168.1.151
          node_id: 3
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/bazaar_root_key 
    vms:
      children:
        managers:
          hosts:
            manager-110:
              ansible_host: 192.168.1.10
            manager-220:
              ansible_host: 192.168.1.20
            manager-330:
              ansible_host: 192.168.1.30
        workers:
          hosts:
            worker-113:
              ansible_host: 192.168.1.13
            worker-222:
              ansible_host: 192.168.1.22
            worker-332:
              ansible_host: 192.168.1.32
            # worker-442:
            #   ansible_host: 192.168.1.42