
# - name: Download Nomad binary
#   get_url:
#     url: "https://releases.hashicorp.com/nomad/{{ common_nomad_version }}/nomad_{{ common_nomad_version }}_linux_amd64.zip"
#     dest: "/tmp/nomad.zip"
#   retries: 3
#   delay: 10
#   register: download_result
#   until: download_result is succeeded

# - name: Unzip Nomad binary
#   unarchive:
#     src: "/tmp/nomad.zip"
#     dest: "/usr/local/bin"
#     remote_src: true

- name: Ensure Nomad binary is executable
  file:
    path: /usr/local/bin/nomad
    mode: '0755'
    state: file

- name: Create Nomad system user
  user:
    name: nomad
    create_home: no
    shell: /bin/false

- name: Create Nomad directories
  file:
    path: "{{ item }}"
    owner: nomad
    group: nomad
    state: directory
    mode: "0755"
  loop:
    - /etc/nomad
    - /opt/nomad

- name: Add nomad user to sudoers for passwordless privileges
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: 'nomad ALL=(ALL) NOPASSWD:ALL'
    state: present
