---
- name: Stop existing VMs
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_secret }}"
    validate_certs: false
    node: "bazaar-{{ item.node_id }}"
    vmid: "{{ item.vm_id }}"
    state: stopped
  when: "'bazaar-' ~ item.node_id == inventory_hostname"
  loop: "{{ vm_definitions }}"