---
- name: Configure Debian hosts' networking
  hosts: all
  become: yes

  vars:
    static_ip_config:
      # ls /sys/class/net
      interface_name: enp2s0 
      gateway: 192.168.1.1
      netmask: 255.255.255.0
      dns: 8.8.8.8

  tasks:
    - name: Comment out the enterprise repository
      lineinfile:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        regexp: '^deb https://enterprise.proxmox.com/debian/pve'
        state: absent

    - name: Add the non-subscription repository
      lineinfile:
        path: /etc/apt/sources.list
        line: 'deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription'
        state: present
        
    - name: Update and upgrade the system
      apt:
        update_cache: yes
        upgrade: dist


    - name: Install necessary dependencies
      apt:
        name: ['wget', 'curl', 'gnupg']
        state: present

    - name: Set static IP address
      copy:
        dest: /etc/network/interfaces
        content: |
          auto lo
          iface lo inet loopback

          iface {{ static_ip_config.interface_name }} inet manual

          auto vmbr0
          iface vmbr0 inet static
                  address {{ hostvars[inventory_hostname].ansible_host }}/24
                  gateway {{ static_ip_config.gateway }}
                  bridge-ports {{ static_ip_config.interface_name }}
                  bridge-stp off
                  bridge-fd 0                  

    - name: Ensure loopback entry exists
      lineinfile:
        path: /etc/hosts
        line: "127.0.0.1 localhost"
        create: yes
        state: present

    - name: Add all other nodes to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item].ansible_host }} {{ item }}"
        create: yes
        state: present
      loop: "{{ groups['all'] }}"