---
- name: Install and configure Proxmox VE cluster
  hosts: all
  become: yes
  vars:
    cluster_name: bazaar-prod
    first_node_ip: 192.168.1.195  # Replace with the IP of your first node

  tasks:
    - name: Install prerequisites
      apt:
        name: ['wget', 'curl', 'gnupg', 'lsb-release']
        state: present

    - name: Add Proxmox GPG key
      apt_key:
        url: "https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg"
        state: present

    - name: Update apt cache
      apt:
        update_cache: true

    - name: Add Proxmox repository
      apt_repository:
        repo: "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription"
        state: present

    - name: Install Proxmox kernel
      apt:
        name: proxmox-default-kernel
        state: present

    - name: Reboot after kernel installation
      reboot:
        msg: "Rebooting after Proxmox VE installation"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 5
        post_reboot_delay: 10      

    - name: Install Proxmox VE packages
      apt:
        name: ['proxmox-ve', 'postfix', 'open-iscsi' ,'chrony', 'python3-proxmoxer']
        state: present

    - name: Remove Debian kernel
      apt:
        name: linux-image-amd64
        state: absent
        purge: true

    - name: Update GRUB
      command: update-grub

    - name: Remove conflicting packages
      apt:
        name:
          - os-prober
        state: absent
      ignore_errors: yes

    # # Create cluster manually
    # - name: Initialize the cluster on the first node
    #   command: pvecm create "{{ cluster_name }}"
    #   when: ansible_host == first_node_ip
    #   register: cluster_init

    # - name: Join the cluster
    #   command: pvecm add "{{ first_node_ip }}"
    #   when: ansible_host != first_node_ip

    # - name: Check cluster status
    #   command: pvecm status
    #   register: cluster_status

    # - debug:
    #     var: cluster_status.stdout_lines
