- name: Enable local-lvm in Proxmox VE
  hosts: bazaar-1
  become: true
  tasks:
    - name: Check if pve volume group exists
      command: vgs --noheadings -o vg_name
      register: vgs_output
      changed_when: false

    - name: Fail if pve volume group does not exist
      fail:
        msg: "Volume group 'pve' not found. Ensure Proxmox VE is installed properly."
      when: "'pve' not in vgs_output.stdout_lines"

    - name: Check if local-lvm thin pool exists
      command: lvs --noheadings -o lv_name pve
      register: lvs_output
      changed_when: false

    - name: Create thin pool for local-lvm if not exists
      command: lvcreate --type thin-pool -L 100G -n vm-thinpool pve
      when: "'vm-thinpool' not in lvs_output.stdout_lines"

    - name: Add local-lvm to Proxmox storage configuration
      lineinfile:
        path: /etc/pve/storage.cfg
        insertafter: EOF
        line: |
          lvmthin: local-lvm
              thinpool vm-thinpool
              vgname pve
              content rootdir,images
      when: "'local-lvm' not in lookup('file', '/etc/pve/storage.cfg')"

    - name: Reload Proxmox storage configuration
      shell: pvesm status
      register: storage_status

    - name: Debug storage status
      debug:
        var: storage_status.stdout
