- name: Clone VM from Cloud-Init Template
  hosts: bazaar-1
  become: true
  vars_files:
  - ../secrets.yml
  vars:
  - template_name: "debian-12.cloudinit-template"
  - node_target: "bazaar-1"
  - new_vm_name: "test-vm.dev1.bazaar.com"

  tasks:
    - name: Clone a VM from the template
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_api_user }}"
        api_token_id: "{{ proxmox_api_token_id }}"
        api_token_secret: "{{ proxmox_api_secret }}"
        validate_certs: false
        node: "{{ node_target }}"
        name: "{{ new_vm_name }}"
        clone: "{{ template_name }}"
        full: false
        state: present
        # memory: 2048
        # cores: 2
        # sockets: 1
        # net:
        #   net0: virtio,bridge=vmbr0
      register: clone_result

    - name: Debug clone result
      debug:
        var: clone_result
