global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https
  websecure:
    address: ":443"
    http:
      tls: {}  # Enable TLS for this entrypoint

api:
  dashboard: true
  insecure: false  # Set to true if you want the dashboard exposed (not recommended publicly)

providers:
  file:
    directory: /etc/traefik
    watch: true
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

tls:
  certificates:
   - certFile: /run/secrets/cloudflare_cert.pem
     keyFile: /run/secrets/cloudflare_key.key

# tls:
#   stores:
#     default:
#       defaultCertificate:
#         certFile: "/run/secrets/cloudflare_cert.pem"
#         keyFile: "/run/secrets/cloudflare_key.key"

# tls:
#   stores:
#     default:
#       defaultGeneratedCert:
#         resolver: cloudflare
#         domain:
#           main: bazaarlab.net
#           sans:
#             - status.bazaarlab.net
#             - traefik.bazaarlab.net