---
- name: Start VMs
  hosts: pve_nodes
  become: true
  vars_files:
  - ../vars/secrets.yml
  - ../vars/vm_definitions.yml
  tasks:
    - name: Start VMs
      include_tasks: tasks/start_vms.yml  

- name: Deploy Hashicorp common software
  hosts: vms
  become: true
  vars_files:
  - ../vars/secrets.yml
  roles:
    - common


- name: Deploy Nomad
  hosts: servers
  become: true
  vars_files:
  - ../vars/secrets.yml
  roles:
    # - name: Create root, intermediate CA for Vault
    #   role: kencx.ansible_collection.ssl
    #   become: true
    #   run_once: true
    - role: vault
    - role: consul-template
    - role: consul
    - role: nomad


- name: Deploy client configuration
  hosts: clients
  become: true
  vars_files:
  - ../vars/secrets.yml
    - role: vault
      vars:
        vault_server: false
    - role: consul-template
    - role: consul
      vars:
        consul_server: false
        consul_client: true
    - role: nomad
      vars:
        nomad_server: false
        nomad_client: true